version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend/public:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
